
DROP TABLE SAC;
DROP TABLE CHAUSSURE;
DROP TABLE HAUT;
DROP TABLE BAS;
DROP TABLE AUTRE;
DROP TABLE FORME_VETEMENT;
DROP TABLE VETEMENT;
DROP TABLE MATIERE_SAISON;
DROP TABLE CONTENU;
DROP TABLE DRESSING;
DROP TABLE UTILISATEUR;

